<!DOCTYPE html>
<html>

<head>
    <meta charset="UTF-8">
    <title>Mon premier site web en php</title>
    <link href="css/stylesheet.css" rel="stylesheet" type="text/css" />
</head>

<body>
    <?php require_once 'section/entete.phtml'; ?>
    <?php require_once 'section/menu.phtml'; ?>

    <div id="contenu">
        <?php require_once 'section/retroaction.phtml'; ?>


        <?php
        foreach ($shweets as $shweet)
        {
            echo '<li><a href="index.php?ctrl=blogue&action=consulter&idblogue=' . $blogue->getId() . '">' . $blogue->getTexte() . '</a></li>';
        }
        ?>

    </div>

    <?php require_once 'section/pied.phtml'; ?>
</body>

</html>