<!DOCTYPE html>
<html>

<head>
    <meta charset="UTF-8">
    <title>Mon premier site web en php</title>
    <link href="css/stylesheet.css" rel="stylesheet" type="text/css" />
</head>

<body>
    <?php require_once 'section/entete.phtml'; ?>
    <?php require_once 'section/menu.phtml'; ?>

    <div id="contenu">
        <?php require_once 'section/retroaction.phtml'; ?>
        <div style="width: 70%; margin-left:auto ;margin-right:auto ;">
            <div>
                <img src=<?php echo $utilisateur->getAvatar()->getUrl() ?> alt="N.D." width="200" height="200">
                <h4><?php echo $utilisateur->getUsername() ?> </h4>
                <p><?php echo $utilisateur->getBio() ?> </p>
                <table>
                    <tbody>

                        <tr>
                            <td><strong>LOCALISATION:</strong></td>
                            <td>
                                <p><?php echo $utilisateur->getLocalisation() ?> </p>
                            </td>
                        </tr>
                        <tr>
                            <td><strong>A REJOINT LE:</strong></td>
                            <td>
                                <p><?php echo $utilisateur->getDtrejoint() ?></p>
                            </td>
                        </tr>
                    </tbody>
                </table>
            </div>
            <div class='border'></div>
            <?php  if (isset($session) && $utilisateur->getId() == $session->getId())
                    {?>
            <form id="formulaireShweetter" method="post" action="index.php">
                <div>
                    <textarea name="texte" id="post-field" class="post-field" placeholder="Écris un Shweet!" minlength="1" maxlength="255" required=""></textarea>
                    <div>
                        <input type="hidden" name="ctrl" value="shweet">
                        <input type="hidden" name="action" value="shweetter">
                        <button class="btn btn-success px-4 py-1">Shwitter!!!</button>
                    </div>
                </div>
            </form>
            <?php }?>
            <div class='border'></div>
            <?php
            $session =  $_SESSION['utilisateur'];
            foreach ($shweets as $shweet)
            {
                echo "
                        <div>
                            <img src=" . $shweet->getAuteur()->getAvatar()->getUrl() . " alt='N.D.' width='75' height='75'>
                            <a href='index.php?ctrl=Page&action=afficherProfil&id=" . $shweet->getId() . "'>" . $shweet->getAuteur()->getUsername() . "</a>
                            <p class='petit-texte'>Publié le " . $shweet->getDateCreation() . "</p>
                            <div>
                                <div>
                                    <p>" . $shweet->gettexte() . "</p>
                                </div>";
                if (isset($session) && $shweet->getAuteur()->getId() == $session->getId())
                {
                    echo "<form method='post' action='index.php'>
                                    <input type='submit' class='btn btn-link' value='Supprimer'>
                                    <input type='hidden' name='shweet-id' value=" . $shweet->getId() . ">
                                    <input type='hidden' name='ctrl' value='shweet'>
                                    <input type='hidden' name='action' value='supprimer'>
                                    <input type='hidden' name='profil-origine-id' value=" . $utilisateur->getId() . ">
                                </form>";
                }
                echo "<hr style='border: 1px dashed black;'>
                                <div class='kids'>";
                foreach ($enfants as $enfant)
                {
                    if ($enfant->getParent() == $shweet->getId())
                    {
                        echo "
                                            <div class='kids'>
                                                <img src=" . $enfant->getAuteur()->getAvatar()->getUrl() . " alt='N.D.' width='75' height='75'>
                                                <a href='index.php?ctrl=page&action=afficherProfil&id=" . $enfant->getId() . "'>" . $enfant->getAuteur()->getUsername() . "</a>
                                                <p>" . $enfant->gettexte() . "</p>";
                        if (isset($session) && $shweet->getAuteur()->getId() == $session->getId())
                        {
                                           echo"<form method='post' action='index.php'>
                                                    <input type='submit' class='btn btn-link' value='Supprimer'>
                                                    <input type='hidden' name='shweet-id' value=" . $enfant->getId() . ">
                                                    <input type='hidden' name='ctrl' value='shweet'>
                                                    <input type='hidden' name='action' value='supprimer'>
                                                    <input type='hidden' name='profil-origine-id' value=" . $utilisateur->getId() . ">
                                                </form>";
                        }
                                       echo"</div>
                                            <hr style='border: 1px dashed black;'>";
                    }
                }
                echo "
                                 </div>
                                    <form class='comment-form' method='post' action='index.php'>
                                        <div class='post-comment' align='right'>
                                            <img src='".$session->getAvatar()->getUrl()."' alt='kevindelaval' width='50' height='50'>
                                            <input type='text' class='form-control' name='texte' placeholder='Répondre...' minlength='1' maxlength='255' required=''>
                                            <input type='hidden' name='parent_id' value=" . $shweet->getId() . ">
                                            <input type='hidden' name='ctrl' value='shweet'>
                                            <input type='hidden' name='action' value='commenter'>
                                            <input type='hidden' name='profil-origine-id' value=" . $utilisateur->getId() . ">
                                            <button class='btn btn-success px-4 py-1'>Commenter</button>
                                        </div>
                                    </form>
                                 <div class='border'></div>
                            </div>
                        </div>
                    ";
            }
            ?>
        </div>
    </div>

    <?php require_once 'section/pied.phtml'; ?>
</body>

</html>